name: fototarzia
favicon: null
layout_spectrum: 0.8082007574848831
typography_spectrum: 0.31300330348312855
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#009fe3'
    - '#1d1d1b'
    - '#979795'
    - '#0b719c'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
